---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: jupyterlab

---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-pvc
  namespace: jupyterlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    name: jupyterlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: jupyterlab
  template:
    metadata:
      labels:
        name: jupyterlab
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      initContainers:
        - name: set-pvc-permissions
          image: busybox
          command: ["/bin/sh", "-c", "chmod -R 777 /data"]
          volumeMounts:
            - mountPath: /data
              name: jupyterlab-data
      containers:
        - name: jupyterlab
          image: gcr.io/PROJECT_ID/IMAGE_API:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --LabApp.token='emd' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
          envFrom:
            - secretRef:
                name: gcp-credentials
            - secretRef:
                name: vault-credentials
          volumeMounts:
            - name: google-service-account
              mountPath: /credentials/
              readOnly: true
            - name: jupyterlab-data
              mountPath: /home/jovyan
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 5120Mi
              cpu: 2500m
        - name: pvc-backup
          image: ghcr.io/prefeitura-rio/pvc-backup:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: backup-config
          volumeMounts:
            - name: google-service-account
              mountPath: /credentials/
              readOnly: true
            - name: jupyterlab-data
              mountPath: /backup
      restartPolicy: Always
      volumes:
        - name: jupyterlab-data
          persistentVolumeClaim:
            claimName: jupyterlab-pvc
        - name: google-service-account
          secret:
            secretName: google-service-account

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    name: jupyterlab
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab
