metadata:
  display_name: "Escritorio de Dados - Default"
  python_version: "3.9"
  use_poetry: false

dependencies:
  - pandas
  - numpy
  - basedosdados==2.0.0b15
  - scipy
  - matplotlib
  - seaborn
  - loguru
  - plotly
  - geopandas==0.14.2
  - descartes
  - pygeos
  - Rtree
  - gspread
  - hvac
  - openpyxl
  - diagrams
  - graphviz
  - kaleido
  - google-api-python-client
  - geolocate
  - lxml
  - html5lib
  - tabula
  - h3pandas
  - opencv-python
  - openai